vertex_count(uint)
v_x(float) v_y(float)
...
edge_count(uint)
v0_id(size_t) v1_id(size_t) node0_id(size_t) node1_id(size_t)
...
obstacle_count(uint)
v0_id(size_t) v1_id(size_t) node_id(size_t) nxt_obst_id(size_t)
...
node_group_name(string)
node_count(uint)
center_x(float) center_y(float)
poly_vert_count(uint) poly_vert_id1(uint) poly_vert_id2(uint) ...
poly_A(float) poly_B(float) poly_C(float)
edge_count(uint) e1_id(uint) e2_id(uint) ...
obst_count(uint) o1_id(uint) o2_id(uint) ...
